In [2]:
import torch 
import numpy as np

x_data = [[1, 2], [3, 4]]
x_data = torch.tensor(x_data)

x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3796, 0.6802],
        [0.8896, 0.3199]]) 



In [28]:
tensor = torch.rand(3, 3)
tensor[:,1] = 1
tensor[0,0] = 6
tensor[2,2] = 9

# pad tensor with 0's
print(f'Original tensor: \n {tensor} \n')
tensor = torch.nn.functional.pad(tensor, (1, 1, 1, 1), value=0)
print(f'Padded tensor: \n {tensor} \n')

# t1 = torch.cat([tensor, tensor], dim=1)
# print(t1)

Original tensor: 
 tensor([[6.0000, 1.0000, 0.9387],
        [0.5687, 1.0000, 0.8997],
        [0.3619, 1.0000, 9.0000]]) 

Padded tensor: 
 tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 6.0000, 1.0000, 0.9387, 0.0000],
        [0.0000, 0.5687, 1.0000, 0.8997, 0.0000],
        [0.0000, 0.3619, 1.0000, 9.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000]]) 

