Secret recipe of CNN:
    not predefined filters -> filters with learnable parameters.

You can predefine filters/kernels if you initialize the weights,
but if you don't they use randomized. 

In [13]:
import torch
import torch.nn as nn

testData = torch.randn(1, 1, 4, 4)

print(f"test data shape: \n{testData}")
conv_layer = nn.Conv2d(1, 1, kernel_size=3, stride=1, padding=1)
print(conv_layer)

# forward pass
output = conv_layer(testData)
print(f"output shape: \n{output}")

test data shape: 
tensor([[[[-0.7860, -1.0053,  0.5453, -0.5328],
          [-0.7226, -1.8749, -0.7743,  1.2109],
          [ 0.3602, -0.1621,  0.5869,  0.4287],
          [ 1.2739,  0.6832, -0.2268,  0.2863]]]])
Conv2d(1, 1, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
output shape: 
tensor([[[[ 0.2102,  0.5440,  0.0836, -0.3769],
          [-0.4715, -0.2460,  0.9337,  0.0680],
          [-0.2822, -0.2478,  0.4474,  0.4727],
          [ 0.4165, -0.4146,  0.0848,  0.1182]]]],
       grad_fn=<ConvolutionBackward0>)


Convolution has some weaknesses, if we shrink the output size, we put less emphasis on edge pixels
Now, use padding

Two types of convolution types:
    1. Valid convolution: no padding 
    2. Same convolution: pad so input and output are same.

In [3]:

x_data = [[1, 2], [3, 4]]
tensor0 = torch.tensor(x_data)
tensor1 = torch.nn.functional.pad(tensor0, (1, 1, 1, 1), value=0)
print(tensor1)

tensor([[0, 0, 0, 0],
        [0, 1, 2, 0],
        [0, 3, 4, 0],
        [0, 0, 0, 0]])
